services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    secrets:
      - db_password
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://warehouse-postgressql.postgres.database.azure.com:5432/postgres?sslmode=require'
      - 'SPRING_DATASOURCE_USERNAME=super_admin'
      - 'SPRING_CONFIG_IMPORT=optional:configtree:/run/secrets/'
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'APP_CORS_ALLOWED_ORIGINS=http://localhost:3000'
    ports:
      - '8080:8080'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - server

secrets:
  db_password:
    file: ./secrets/db_password
