ALTER TABLE inventory_item
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE inventory_item
    DROP CONSTRAINT inventory_item_pkey;

ALTER TABLE inventory_item
    ADD CONSTRAINT inventory_item_pkey PRIMARY KEY (id);

ALTER TABLE inventory_item
    ADD CONSTRAINT inventory_item_sku_warehouse_key UNIQUE (sku, warehouse_id);
