CREATE TABLE IF NOT EXISTS warehouse (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(128) NOT NULL,
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    max_capacity DOUBLE PRECISION NOT NULL CHECK (max_capacity > 0),
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY  (id)
);