CREATE TABLE IF NOT EXISTS product (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sku        VARCHAR(64) NOT NULL UNIQUE,
    name       VARCHAR(128) NOT NULL,
    category   VARCHAR(64),
    length_cm  DOUBLE PRECISION NOT NULL CHECK (length_cm > 0),
    width_cm   DOUBLE PRECISION NOT NULL CHECK (width_cm > 0),
    height_cm  DOUBLE PRECISION NOT NULL CHECK (height_cm > 0),
    weight_kg  DOUBLE PRECISION NOT NULL CHECK (weight_kg > 0),
    PRIMARY KEY (id)
);