CREATE TABLE IF NOT EXISTS shipment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    warehouse_id      BIGINT NOT NULL,
    order_status      VARCHAR(32) NOT NULL,
    expected_arrival  TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_shipment_warehouse
        FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)
);

CREATE INDEX IF NOT EXISTS idx_shipment_warehouse_status
    ON shipment (warehouse_id, order_status);
